### ISSUE TITLE
How can I fix it 

### ISSUE THREAD

**Issue by hossaindev** [adarsh-goel/filestreambot#13]
![IMG_20220314_231650_592](https://user-images.githubusercontent.com/97832593/158225575-32b41dd9-884c-406e-977a-17c38597e80e.jpg)

**Comment by DeekshithSH** [comment]
> ![IMG_20220314_231650_592]

Check Your MongoDB URI

your DATABASE_URL is Something like this?
`mongodb+srv://TelegramToLink:123456@telegramfiletolink.ocaal.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`

- `123456` is password
- `myFirstDatabase` is Your databse name
